### PR TITLE
Fix CFG denoiser.

### PR DESCRIPTION
**Pull request by slouffka**
Made it work but not sure if everything is correct. As I don't fully understand the logic of how denoiser works. Though I referred to a comfyui code to fix cfg denoiser and denoise workflow from efficiency nodes does not produce error anymore.

Please review and let me know if there are any issues with this PR.

### CODE REVIEW

**Comment by slouffka** [comment]
I'm referring to this workflow to be clear: workflows/SDXL_base_refine_noise_workflow.png

**Comment by jags111** [comment]
sure will test and update same thanks

**Comment by slouffka** [comment]
Also fixes https://github.com/jags111/efficiency-nodes-comfyui/issues/95, https://github.com/jags111/efficiency-nodes-comfyui/issues/94 and https://github.com/jags111/efficiency-nodes-comfyui/issues/76

**Comment by slouffka** [comment]
I've been using "Noise Control Script" for couple days and I'm pretty happy with final images. So I assume it works as intended.

**Pull request merged**
